# Generated by Django 6.1 on 2026-08-13 01:52

import authentication.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's unique email address. Used as the login identifier.", max_length=254, unique=True)),
                ('first_name', models.CharField(help_text="User's first name.", max_length=150)),
                ('last_name', models.CharField(help_text="User's last name.", max_length=150)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has confirmed their email address via OTP.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this account is active. Admins toggling this off blocks state-changing actions across the platform, but does NOT block login.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the Django admin site.')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='6-digit zero-padded numeric OTP code.', max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('password_reset', 'Password Reset')], default='register', help_text='What this OTP is for.', max_length=20)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this OTP has already been consumed.')),
                ('expires_at', models.DateTimeField(help_text='Moment after which this OTP is no longer valid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user this OTP was issued to.', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text="Hashed reset token (stored via Django's make_password).", max_length=255)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has already been consumed.')),
                ('expires_at', models.DateTimeField(help_text='Moment after which this token is no longer valid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user requesting the password reset.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
