# Generated by Django 6.1 on 2026-08-13 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Must be >= MIN_WITHDRAWAL_AMOUNT and <= available balance at request time.', max_digits=18)),
                ('wallet_address', models.CharField(help_text='Destination USDT-TRC20 wallet address.', max_length=255)),
                ('network', models.CharField(default='USDT-TRC20', help_text='Fixed — the only supported payout network.', max_length=50)),
                ('status', models.CharField(choices=[('pending_otp', 'Pending OTP'), ('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_otp', help_text='pending_otp -> pending -> completed/rejected.', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal_withdrawal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='6-digit numeric OTP, zero-padded.', max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(help_text='now() + OTP_EXPIRY_MINUTES at creation time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='withdrawal.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_withdrawalotp',
            },
        ),
    ]
