# Generated by Django 6.1 on 2026-08-13 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinChangeOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='6-digit numeric OTP, zero-padded.', max_length=6)),
                ('new_pin_hash', models.CharField(help_text='Hashed pending new PIN, held here until the OTP is confirmed.', max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(help_text='now() + OTP_EXPIRY_MINUTES at creation time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_change_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIN Change OTP',
                'verbose_name_plural': 'PIN Change OTPs',
                'db_table': 'transaction_pin_pinchangeotp',
            },
        ),
        migrations.CreateModel(
            name='TransactionPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_hash', models.CharField(help_text='Hashed 4-digit transaction PIN (Django make_password). Never stored or returned in plain text.', max_length=128)),
                ('is_set', models.BooleanField(default=False, help_text='Whether the user has completed their first-time PIN setup.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction PIN',
                'verbose_name_plural': 'Transaction PINs',
                'db_table': 'transaction_pin_transactionpin',
            },
        ),
    ]
