# Generated by Django 6.1 on 2026-08-13 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth.", null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='One of: male, female, other.', max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, help_text="User's nationality.", max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Country of residence.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/region of residence.', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City of residence.', max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, help_text='Street address.', max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code.', max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], help_text='One of: employed, self_employed, unemployed, student, retired.', max_length=20, null=True)),
                ('employer_name', models.CharField(blank=True, help_text='Name of current employer, if any.', max_length=150)),
                ('occupation', models.CharField(blank=True, help_text='Current occupation/job title.', max_length=150)),
                ('annual_income_range', models.CharField(blank=True, choices=[('under_10k', 'Under $10,000'), ('10k_50k', '$10,000 - $50,000'), ('50k_100k', '$50,000 - $100,000'), ('100k_500k', '$100,000 - $500,000'), ('above_500k', 'Above $500,000')], help_text='One of: under_10k, 10k_50k, 50k_100k, 100k_500k, above_500k.', max_length=20, null=True)),
                ('source_of_funds', models.CharField(blank=True, choices=[('salary', 'Salary'), ('business_income', 'Business Income'), ('investments', 'Investments'), ('inheritance', 'Inheritance'), ('other', 'Other')], help_text='One of: salary, business_income, investments, inheritance, other.', max_length=20, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], help_text='One of: passport, national_id, drivers_license, voters_card.', max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, help_text='Government ID number.', max_length=100, null=True)),
                ('id_issuing_country', models.CharField(blank=True, help_text='Country that issued the ID.', max_length=100, null=True)),
                ('id_expiry_date', models.DateField(blank=True, help_text='Expiry date of the government ID.', null=True)),
                ('trading_experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], help_text='One of: beginner, intermediate, advanced, professional.', max_length=20, null=True)),
                ('years_of_trading_experience', models.PositiveIntegerField(blank=True, help_text='Number of years of trading experience.', null=True)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='One of: low, medium, high.', max_length=10, null=True)),
                ('preferred_markets', models.CharField(blank=True, help_text="Free-text/comma-separated list of preferred markets, e.g. 'forex, shares'.", max_length=255)),
                ('is_politically_exposed_person', models.BooleanField(default=False, help_text='Whether the user is a politically exposed person (PEP).')),
                ('agreed_to_terms', models.BooleanField(default=False, help_text='Whether the user has agreed to the KYC terms. Required to submit.')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', help_text='One of: not_submitted, pending, approved, rejected.', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin-only notes, e.g. reason for rejection.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Set automatically when the user submits.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Set automatically when an admin approves or rejects. Never manually editable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user this KYC profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Profile',
                'verbose_name_plural': 'KYC Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
