# Generated by Django 6.1 on 2026-08-15 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_seed_trade_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the trade was opened. Auto-set on creation, but editable afterward by an admin to correct/backdate/postdate for display purposes.'),
        ),
    ]
