# Generated by Django 6.1 on 2026-08-13 01:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds the user can withdraw or invest right now.', max_digits=18)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds currently tied up in active trades.', max_digits=18)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running lifetime total of approved deposits (display stat).', max_digits=18)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running lifetime total of approved withdrawals (display stat).', max_digits=18)),
                ('total_profit_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running lifetime total of trade profits credited (display stat).', max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user this wallet belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('deposit_credit', 'Deposit Credit'), ('withdrawal_debit', 'Withdrawal Debit'), ('trade_lock', 'Trade Lock'), ('trade_unlock_credit', 'Trade Unlock Credit')], help_text='One of: deposit_credit, withdrawal_debit, trade_lock, trade_unlock_credit.', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; direction is implied by entry_type.', max_digits=18)),
                ('balance_after_available', models.DecimalField(decimal_places=2, help_text='Snapshot of available_balance after this entry.', max_digits=18)),
                ('balance_after_locked', models.DecimalField(decimal_places=2, help_text='Snapshot of locked_balance after this entry.', max_digits=18)),
                ('reference', models.CharField(blank=True, help_text="e.g. 'Deposit #123', 'Trade #45 payout'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(help_text='The wallet this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Ledger Entry',
                'verbose_name_plural': 'Wallet Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
