# Generated by Django 6.1 on 2026-08-13 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Also serves as the human-visible deposit reference.', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Deposit amount in USD. Must be above the configured minimum.', max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='One of: pending, approved, rejected.', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Optional reason, shown to the user if the deposit is rejected.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Immutable — when the user submitted the request.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Set automatically the moment an admin moves status away from pending. Never manually editable.', null=True)),
                ('user', models.ForeignKey(help_text='The user who requested this deposit.', on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
