# Generated by Django 6.1 on 2026-08-15 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the user submitted the request. Auto-set on creation, but editable afterward by an admin to correct/backdate/postdate for display purposes. The API only ever exposes this read-only.'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Auto-set the moment an admin approves/rejects, but freely editable afterward for corrections.', null=True),
        ),
    ]
